---
- name: Install from kubic if not ubuntu 22.04 lts release
  block:
  - name: Add podman gpg key
    ansible.builtin.apt_key:
      url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version }}/Release.key
      state: present
  - name: Add kubic repository
    ansible.builtin.apt_repository:
      repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version }}/ /
      state: present
      filename: podman
  when: ansible_distribution_version != "22.04"

- name: Install podman
  ansible.builtin.apt:
    name: podman

- name: Install podman-compose
  ansible.builtin.pip:
    name: podman-compose